//sirve esto para hacer pruebas, esta hardcoreado

export const products = [
  {
    id: 1,
    title: "Slime",
    price: 200,
    stock: 10,
    description: "Este es un slime comun",
    category: "slimes",
    img: "https://res.cloudinary.com/dnytlq0wc/image/upload/v1677371121/slime_verde_i2qoqy.png",
  },
  {
    id: 2,
    title: "Slime Rojo",
    price: 500,
    stock: 4,
    description: "Este es un slime rojo",
    category: "slimes",
    img: "https://res.cloudinary.com/dnytlq0wc/image/upload/v1677371121/slime_rojo_yfbqwm.png",
  },
  {
    id: 3,
    title: "Slime celeste",
    price: 500,
    stock: 3,
    description: "Este es un slime celeste",
    category: "slimes",
    img: "https://res.cloudinary.com/dnytlq0wc/image/upload/v1677371120/slime_celeste_lydfxi.png",
  },
  {
    id: 4,
    title: "Slime Violeta",
    price: 2000,
    stock: 1,
    description: "Este es un slime violeta",
    category: "slimes",
    img: "https://res.cloudinary.com/dnytlq0wc/image/upload/v1677371121/slime_violeta_jigtte.png",
  },
  {
    id: 5,
    title: "Moneda",
    price: 10000,
    stock: 1,
    description: "Esta es una moneda",
    category: "otrasCosas",
    img: "https://res.cloudinary.com/dnytlq0wc/image/upload/v1679000272/carryCoin_ys2hve.png",
  },
  {
    id: 6,
    title: "Pocion menor de Mana",
    price: 150,
    stock: 100,
    description: "Es una pocion menor de mana",
    category: "otrasCosas",
    img: "https://res.cloudinary.com/dnytlq0wc/image/upload/v1679000272/tuboDeEnsayo_1_srrmfr.png",
  },
  {
    id: 7,
    title: "Pocion menor de Vida",
    price: 150,
    stock: 100,
    description: "Es una pocion menor de vida",
    category: "otrasCosas",
    img: "https://res.cloudinary.com/dnytlq0wc/image/upload/v1679000272/tuboDeEnsayo_rojo_yfuz07.png",
  },
  {
    id: 8,
    title: "Pocion menor Restauradora",
    price: 350,
    stock: 100,
    description: "Es una pocion menor restauradora de mana y vida",
    category: "otrasCosas",
    img: "https://res.cloudinary.com/dnytlq0wc/image/upload/v1679000272/tuboDeEnsayo_celeste_piwm4i.png",
  },
];
